library(shiny)
library(here)
ui <- fluidPage(
    titlePanel("Statistical Applications & Analysis Dashboard"), # nolint
    sidebarLayout(
        sidebarPanel( # nolint
            h3("Run Statistical Projects"), # nolint
            actionButton("run_retail_forecast", "Retail Demand Forecasting"),
            br(), br(),
            actionButton("run_sentiment_analysis", "Sentiment Analysis"),
            br(), br(),
            actionButton("run_sales_analysis", "Sales Data Analysis"),
            br(), br(),
            actionButton("run_eda_iris", "EDA on Iris Dataset"),
            br(), br(),
            actionButton("run_probability_simulation", "Probability Distribution Simulation"), # nolint
            br(), br(),
            actionButton("run_estimation_theory", "Theory of Estimation"),
            br(), br(),
            actionButton("run_hypothesis_testing", "Hypothesis Testing")
        ), # nolint
        mainPanel(
            h4("Project Output:"), # nolint
            verbatimTextOutput("output_text"),
            uiOutput("output_figure")
        ) # nolint
    ) # nolint
)
server <- function(input, output, session) {
    observeEvent(input$run_retail_forecast, { # nolint
        output$output_text <- renderPrint({ # nolint
            req(file.exists(here("R/01_retail_demand_forecasting.R"))) # nolint
            temp_env <- new.env()
            capture.output(
                source(here("R/01_retail_demand_forecasting.R"), local = temp_env), # nolint
                type = "output"
            ) # nolint
        }) # nolint
        output$output_figure <- renderUI({
            if (file.exists(here("outputs/figures/retail_forecast.png"))) { # nolint
                tags$img(src = "retail_forecast.png", width = "100%") # nolint
            } else { # nolint
                HTML("<p>No forecast plot generated or found.</p>") # nolint
            } # nolint
        }) # nolint
    }) # nolint

    observeEvent(input$run_sentiment_analysis, { # nolint
        output$output_text <- renderPrint({ # nolint
            req(file.exists(here("R/02_sentiment_analysis_reviews.R"))) # nolint
            temp_env <- new.env()
            capture.output(
                source(here("R/02_sentiment_analysis_reviews.R"), local = temp_env), # nolint
                type = "output"
            ) # nolint
        }) # nolint
        output$output_figure <- renderUI({
            HTML("<p>Sentiment analysis results are saved as an RDS file. No plot generated by this script.</p>") # nolint
        }) # nolint
    }) # nolint

    observeEvent(input$run_sales_analysis, { # nolint
        output$output_text <- renderPrint({ # nolint
            req(file.exists(here("R/03_sales_dataset_analysis.R"))) # nolint
            temp_env <- new.env()
            capture.output(
                source(here("R/03_sales_dataset_analysis.R"), local = temp_env), # nolint
                type = "output"
            ) # nolint
        }) # nolint
        output$output_figure <- renderUI({
            HTML("<p>Sales data analysis provides console output for correlations. No plot generated by this script.</p>") # nolint
        }) # nolint
    }) # nolint

    observeEvent(input$run_eda_iris, { # nolint
        output$output_text <- renderPrint({ # nolint
            req(file.exists(here("R/04_exploratory_data_analysis.R"))) # nolint
            HTML("<p>The 'EDA on Iris Dataset' script includes interactive prompts (readline) which are not directly compatible with a simple Shiny button click without refactoring. It will primarily show the summary and generate the R Markdown report.</p>") # nolint
            temp_env <- new.env()
            capture.output(
                { # nolint
                    library(datasets) # nolint
                    library(rmarkdown)
                    data("iris")
                    summarise_iris <- summary(iris)
                    print(summarise_iris)
                    rmarkdown::render(here("outputs/04_exploratory_data_analysis.Rmd"), output_format = "html_document") # nolint
                    print("R Markdown report generated to outputs/04_exploratory_data_analysis.html") # nolint
                }, # nolint
                type = "output"
            ) # nolint
        }) # nolint
        output$output_figure <- renderUI({
            HTML("<p>EDA output includes console summary and an R Markdown report (04_exploratory_data_analysis.html) saved in the 'outputs' directory.</p>") # nolint
        }) # nolint
    }) # nolint


    observeEvent(input$run_probability_simulation, { # nolint
        output$output_text <- renderPrint({ # nolint
            req(file.exists(here("R/05_probability_distributions_simulation.R"))) # nolint
            temp_env <- new.env()
            capture.output(
                source(here("R/05_probability_distributions_simulation.R"), local = temp_env), # nolint
                type = "output"
            ) # nolint
        }) # nolint
        output$output_figure <- renderUI({
            HTML("<p>Probability distribution plots are generated in the R environment. For a Shiny app, these plots would need to be explicitly captured and displayed using renderPlot().</p>") # nolint
        }) # nolint
    }) # nolint

    observeEvent(input$run_estimation_theory, { # nolint
        output$output_text <- renderPrint({ # nolint
            req(file.exists(here("R/06_theory_of_estimation.R"))) #  nolint
            HTML("<p>The 'Theory of Estimation' script uses interactive inputs (readLines) which are not directly compatible with a simple Shiny button click without refactoring. The plot is generated in the R environment if run manually.</p>") # nolint
        }) # nolint
        output$output_figure <- renderUI({
            HTML("<p>The 'Theory of Estimation' plot (density plot) is generated in the R environment when run manually. Refactoring is needed for direct display in Shiny.</p>") # nolint
        }) # nolint
    }) # nolint

    observeEvent(input$run_hypothesis_testing, { # nolint
        output$output_text <- renderPrint({ # nolint
            req(file.exists(here("R/07_hypothesis_testing_reviews.R"))) # nolint
            temp_env <- new.env()
            capture.output(
                source(here("R/07_hypothesis_testing_reviews.R"), local = temp_env), # nolint
                type = "output"
            ) # nolint
        }) # nolint
        output$output_figure <- renderUI({
            if (file.exists(here("outputs/figures/reviews_helpfulness_boxplot.png"))) { # nolint
                tags$img(src = "reviews_helpfulness_boxplot.png", width = "100%") # nolint
            } else { # nolint
                HTML("<p>No hypothesis testing plot generated or found.</p>") # nolint
            } # nolint
        }) # nolint
    }) # nolint
    output$retail_forecast.png <- renderImage(
        { # nolint
            filename <- normalizePath(file.path(here("outputs/figures"), "retail_forecast.png")) # nolint
            list(src = filename, alt = "Retail Demand Forecast Plot")
        }, # nolint
        deleteFile = FALSE
    ) # nolint

    output$reviews_helpfulness_boxplot.png <- renderImage( # nolint
        { # nolint
            filename <- normalizePath(file.path(here("outputs/figures"), "reviews_helpfulness_boxplot.png")) # nolint
            list(src = filename, alt = "Ratings by Review Helpfulness Boxplot")
        }, # nolint
        deleteFile = FALSE
    ) # nolint
}

shinyApp(ui = ui, server = server)
